//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P\HMAE\INT_NAT\ENV.
        /// </summary>
        internal static string CaminhoDestinoNat {
            get {
                return ResourceManager.GetString("CaminhoDestinoNat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P\HMAE\INT_SOR\ENV.
        /// </summary>
        internal static string CaminhoDestinoSor {
            get {
                return ResourceManager.GetString("CaminhoDestinoSor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.14.124.11\.
        /// </summary>
        internal static string CaminhoOrigem {
            get {
                return ResourceManager.GetString("CaminhoOrigem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.18.214.11\.
        /// </summary>
        internal static string ServidorALP {
            get {
                return ResourceManager.GetString("ServidorALP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.18.182.11\.
        /// </summary>
        internal static string ServidorBET {
            get {
                return ResourceManager.GetString("ServidorBET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.23.85.11\.
        /// </summary>
        internal static string ServidorDIA {
            get {
                return ResourceManager.GetString("ServidorDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.18.188.11\.
        /// </summary>
        internal static string ServidorDIV {
            get {
                return ResourceManager.GetString("ServidorDIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.44.165.11\.
        /// </summary>
        internal static string ServidorGOV {
            get {
                return ResourceManager.GetString("ServidorGOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.18.180.11\.
        /// </summary>
        internal static string ServidorHJK {
            get {
                return ResourceManager.GetString("ServidorHJK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.18.200.11\.
        /// </summary>
        internal static string ServidorITU {
            get {
                return ResourceManager.GetString("ServidorITU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.18.194.11\.
        /// </summary>
        internal static string ServidorJFO {
            get {
                return ResourceManager.GetString("ServidorJFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.23.86.11\.
        /// </summary>
        internal static string ServidorMCU {
            get {
                return ResourceManager.GetString("ServidorMCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.18.222.11\.
        /// </summary>
        internal static string ServidorMOC {
            get {
                return ResourceManager.GetString("ServidorMOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.18.198.11\.
        /// </summary>
        internal static string ServidorPAL {
            get {
                return ResourceManager.GetString("ServidorPAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.18.204.11\.
        /// </summary>
        internal static string ServidorPAS {
            get {
                return ResourceManager.GetString("ServidorPAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.18.190.11\.
        /// </summary>
        internal static string ServidorPMI {
            get {
                return ResourceManager.GetString("ServidorPMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.18.206.11\.
        /// </summary>
        internal static string ServidorPNO {
            get {
                return ResourceManager.GetString("ServidorPNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.44.239.11\.
        /// </summary>
        internal static string ServidorPOC {
            get {
                return ResourceManager.GetString("ServidorPOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.23.87.11\.
        /// </summary>
        internal static string ServidorSJR {
            get {
                return ResourceManager.GetString("ServidorSJR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.18.210.11\.
        /// </summary>
        internal static string ServidorSLA {
            get {
                return ResourceManager.GetString("ServidorSLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.18.186.11\.
        /// </summary>
        internal static string ServidorUDI {
            get {
                return ResourceManager.GetString("ServidorUDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.18.184.11\.
        /// </summary>
        internal static string ServidorURA {
            get {
                return ResourceManager.GetString("ServidorURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALP$.
        /// </summary>
        internal static string SiglaALP {
            get {
                return ResourceManager.GetString("SiglaALP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALPNAT.
        /// </summary>
        internal static string SiglaALP_NAT {
            get {
                return ResourceManager.GetString("SiglaALP_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BET$.
        /// </summary>
        internal static string SiglaBET {
            get {
                return ResourceManager.GetString("SiglaBET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BETNAT.
        /// </summary>
        internal static string SiglaBET_NAT {
            get {
                return ResourceManager.GetString("SiglaBET_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIA$.
        /// </summary>
        internal static string SiglaDIA {
            get {
                return ResourceManager.GetString("SiglaDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIANAT.
        /// </summary>
        internal static string SiglaDIA_NAT {
            get {
                return ResourceManager.GetString("SiglaDIA_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIV$.
        /// </summary>
        internal static string SiglaDIV {
            get {
                return ResourceManager.GetString("SiglaDIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIVNAT.
        /// </summary>
        internal static string SiglaDIV_NAT {
            get {
                return ResourceManager.GetString("SiglaDIV_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOV$.
        /// </summary>
        internal static string SiglaGOV {
            get {
                return ResourceManager.GetString("SiglaGOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOVNAT.
        /// </summary>
        internal static string SiglaGOV_NAT {
            get {
                return ResourceManager.GetString("SiglaGOV_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HJK$.
        /// </summary>
        internal static string SiglaHJK {
            get {
                return ResourceManager.GetString("SiglaHJK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HJKNAT.
        /// </summary>
        internal static string SiglaHJK_NAT {
            get {
                return ResourceManager.GetString("SiglaHJK_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITU$.
        /// </summary>
        internal static string SiglaITU {
            get {
                return ResourceManager.GetString("SiglaITU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITUNAT.
        /// </summary>
        internal static string SiglaITU_NAT {
            get {
                return ResourceManager.GetString("SiglaITU_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JFO$.
        /// </summary>
        internal static string SiglaJFO {
            get {
                return ResourceManager.GetString("SiglaJFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JFONAT.
        /// </summary>
        internal static string SiglaJFO_NAT {
            get {
                return ResourceManager.GetString("SiglaJFO_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCU$.
        /// </summary>
        internal static string SiglaMCU {
            get {
                return ResourceManager.GetString("SiglaMCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCUNAT.
        /// </summary>
        internal static string SiglaMCU_NAT {
            get {
                return ResourceManager.GetString("SiglaMCU_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC$.
        /// </summary>
        internal static string SiglaMOC {
            get {
                return ResourceManager.GetString("SiglaMOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOCNAT.
        /// </summary>
        internal static string SiglaMOC_NAT {
            get {
                return ResourceManager.GetString("SiglaMOC_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAL$.
        /// </summary>
        internal static string SiglaPAL {
            get {
                return ResourceManager.GetString("SiglaPAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PALNAT.
        /// </summary>
        internal static string SiglaPAL_NAT {
            get {
                return ResourceManager.GetString("SiglaPAL_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAS$.
        /// </summary>
        internal static string SiglaPAS {
            get {
                return ResourceManager.GetString("SiglaPAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASNAT.
        /// </summary>
        internal static string SiglaPAS_NAT {
            get {
                return ResourceManager.GetString("SiglaPAS_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMI$.
        /// </summary>
        internal static string SiglaPMI {
            get {
                return ResourceManager.GetString("SiglaPMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMINAT.
        /// </summary>
        internal static string SiglaPMI_NAT {
            get {
                return ResourceManager.GetString("SiglaPMI_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNO$.
        /// </summary>
        internal static string SiglaPNO {
            get {
                return ResourceManager.GetString("SiglaPNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNONAT.
        /// </summary>
        internal static string SiglaPNO_NAT {
            get {
                return ResourceManager.GetString("SiglaPNO_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POC$.
        /// </summary>
        internal static string SiglaPOC {
            get {
                return ResourceManager.GetString("SiglaPOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POCNAT.
        /// </summary>
        internal static string SiglaPOC_NAT {
            get {
                return ResourceManager.GetString("SiglaPOC_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SJR$.
        /// </summary>
        internal static string SiglaSJR {
            get {
                return ResourceManager.GetString("SiglaSJR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SJRNAT.
        /// </summary>
        internal static string SiglaSJR_NAT {
            get {
                return ResourceManager.GetString("SiglaSJR_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLA$.
        /// </summary>
        internal static string SiglaSLA {
            get {
                return ResourceManager.GetString("SiglaSLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLANAT.
        /// </summary>
        internal static string SiglaSLA_NAT {
            get {
                return ResourceManager.GetString("SiglaSLA_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDI$.
        /// </summary>
        internal static string SiglaUDI {
            get {
                return ResourceManager.GetString("SiglaUDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDINAT.
        /// </summary>
        internal static string SiglaUDI_NAT {
            get {
                return ResourceManager.GetString("SiglaUDI_NAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URA$.
        /// </summary>
        internal static string SiglaURA {
            get {
                return ResourceManager.GetString("SiglaURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URANAT.
        /// </summary>
        internal static string SiglaURA_NAT {
            get {
                return ResourceManager.GetString("SiglaURA_NAT", resourceCulture);
            }
        }
    }
}
